pages:
  image: node:v10.1.0
  script:
    - "yarn install"
    - "yarn run build"
    - "cp public/index.html public/404.html"
  cache:
    paths:
    - node_modules/
  artifacts:
    paths:
    - public
  only:
  - master